name: NPM release

on:
  pull_request:
    branches: [ master ]
    types:
      - opened
      - synchronize
      - reopened
      # Triggers the workflow when labels change in the PR
      - labeled
      - unlabeled
  push:
    branches:
      - master

jobs:
  npm-release:
    uses: mapbox/gha/.github/workflows/workflow-release-npm-package.yml@workflow-release-npm-package-v1
    secrets: inherit
    with:
      changelog-file: changelog.md
